### ISSUE TITLE
Submit as module to Node Package Manager (NPM)

### ISSUE THREAD

**Issue by martindale** [andrewplummer/APIConnect#2]
This includes doing some testing with node.js, and submitting it as a module for availability as a server-side module.

**Comment by andrewplummer** [comment]
Yes, great idea... Unfortunately APIConnect is dependent on jQuery, so some work is going to have to be done here, but I agree it's a good idea.

**Comment by martindale** [comment]
It doesn't look like much is _really_ using jQuery, but there is underscore on the server side as a reasonable replacement if you need it.

**Comment by andrewplummer** [comment]
I tried to minimize the point of contact but jQuery is absolutely required for $.ajax and deferred objects. I'll need something for both those. I'm thinking just a curl package and some simple deferred object code (not sure how deferreds work in node).

**Comment by mwawrusch** [comment]
Instead of npm ender (http://ender.no.de/) might be a good option. 
Great work btw.

**Comment by andrewplummer** [comment]
Ender is npm! Btw this is coming very soon!

**Comment by mwawrusch** [comment]
True. Guess I learned something new today :P

**Comment by andrewplummer** [comment]
OK! It's out!
